# Generated by Django 5.0.7 on 2024-08-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_oredered',
            new_name='date_ordered',
        ),
    ]
